//! Cryptographic operations for the distributed system.
//!
//! This module provides the core cryptographic operations for the distributed system.
//! It includes the `PublicKey` and `PrivateKey` types, as well as the `Signature` type.
//!
//! # Public Key
//!
//! The `PublicKey` type is a wrapper around the `VerifyingKey` type from the `ed25519-dalek` crate.
//! It provides a convenient interface for verifying signatures.
//!
//! # Private Key
//!
//! The `PrivateKey` type is a wrapper around the `SigningKey` type from the `ed25519-dalek` crate.
//! It provides a convenient interface for signing messages and generating public keys.
//!
//! # Signature
//!
//! The `Signature` type is a wrapper around the `Signature` type from the `ed25519-dalek` crate.
//! It provides a convenient interface for verifying signatures.
//!
//! # Examples
//!
//! ```ignore
//! use distbench::crypto::{PublicKey, PrivateKey, Signature};
//!
//! let private_key = PrivateKey::generate();
//! let public_key = private_key.pubkey();
//! let signature = private_key.sign(b"Hello, world!");
//! let verified = public_key.verify(b"Hello, world!", &signature);
//! assert!(verified);
//! ```

use ed25519_dalek::{ed25519::signature::Signer, SigningKey, VerifyingKey};
use rand::rngs::OsRng;
use serde::{Deserialize, Serialize};

use crate::signing::Digest;

/// A signature generated by a private key.
#[derive(Serialize, Deserialize, Debug, Clone, Copy)]
pub struct Signature(ed25519_dalek::Signature);

/// A private key used to sign messages and generate public keys.
#[derive(Debug, Clone)]
pub struct PrivateKey(SigningKey);

/// A public key used to verify signatures.
#[derive(Debug, Clone, Copy)]
pub struct PublicKey(VerifyingKey);

impl PrivateKey {
    /// Generates a new private key.
    pub fn generate() -> Self {
        let mut csprng = OsRng;
        let key = SigningKey::generate(&mut csprng);
        Self(key)
    }

    /// Signs a message with the private key.
    pub fn sign(&self, message: &[u8; 32]) -> Signature {
        Signature(self.0.sign(message))
    }

    /// Returns the public key associated with this private key.
    pub fn pubkey(&self) -> PublicKey {
        PublicKey(self.0.verifying_key())
    }

    /// Converts the private key to bytes.
    pub fn to_bytes(&self) -> [u8; 32] {
        self.0.to_bytes()
    }
}

impl PublicKey {
    /// Verifies a signature on a message.
    pub fn verify(&self, message: &[u8; 32], signature: &Signature) -> bool {
        self.0.verify_strict(message, &signature.0).is_ok()
    }

    /// Converts the public key to bytes.
    pub fn to_bytes(&self) -> [u8; 32] {
        self.0.to_bytes()
    }

    /// Creates a public key from bytes.
    pub fn from_bytes(bytes: &[u8; 32]) -> Self {
        Self(VerifyingKey::from_bytes(bytes).expect("Invalid public key bytes"))
    }
}

impl Digest for Signature {
    fn digest(&self) -> [u8; 32] {
        self.0.to_bytes()[..32].try_into().unwrap()
    }
}
