n0:
  host: "n0"
  port: 5000
  neighbours: [n1, n9]
  is_sender: true
  f: 3

n1:
  host: "n1"
  port: 5001
  neighbours: [n0, n2]
  f: 3

n2:
  host: "n2"
  port: 5002
  neighbours: [n1, n3]
  f: 3

n3:
  host: "n3"
  port: 5003
  neighbours: [n2, n4]
  f: 3

n4:
  host: "n4"
  port: 5004
  neighbours: [n3, n5]
  f: 3

n5:
  host: "n5"
  port: 5005
  neighbours: [n4, n6]
  f: 3

n6:
  host: "n6"
  port: 5006
  neighbours: [n5, n7]
  f: 3

n7:
  host: "n7"
  port: 5007
  neighbours: [n6, n8]
  f: 3

n8:
  host: "n8"
  port: 5008
  neighbours: [n7, n9]
  f: 3

n9:
  host: "n9"
  port: 5009
  neighbours: [n8, n0]
  f: 3
