n0:
  listen: 0.0.0.0:5000
  neighbours: [n1, n9]
  is_sender: true
  f: 3

n1:
  listen: 0.0.0.0:5001
  neighbours: [n0, n2]
  f: 3

n2:
  listen: 0.0.0.0:5002
  neighbours: [n1, n3]
  f: 3

n3:
  listen: 0.0.0.0:5003
  neighbours: [n2, n4]
  f: 3

n4:
  listen: 0.0.0.0:5004
  neighbours: [n3, n5]
  f: 3

n5:
  listen: 0.0.0.0:5005
  neighbours: [n4, n6]
  f: 3

n6:
  listen: 0.0.0.0:5006
  neighbours: [n5, n7]
  f: 3

n7:
  listen: 0.0.0.0:5007
  neighbours: [n6, n8]
  f: 3

n8:
  listen: 0.0.0.0:5008
  neighbours: [n7, n9]
  f: 3

n9:
  listen: 0.0.0.0:5009
  neighbours: [n8, n0]
  f: 3
